### ISSUE TITLE
Naming issue

### ISSUE THREAD

**Issue by henrikac** [NeuraLegion/sectester#2]
Since the repo's name is `sectester` this

```yaml
dependencies:
  sec_tester:
    github: NeuraLegion/sec_tester
```
should be changed to
```yaml
dependencies:
  sec_tester:
    github: NeuraLegion/sectester  # <= no underscore :)
```

Also, **1. Fork it (https://github.com/NeuraLegion/sec_tester/fork)** has the same underscore issue.

Another solution would be to just change the repo's name to `sec_tester`.
